// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CancelServerActivitiesRequest struct {
	// The UUID of the activity to cancel.
	ActivityUUID string `pathParam:"style=simple,explode=false,name=activityUUID"`
}

func (o *CancelServerActivitiesRequest) GetActivityUUID() string {
	if o == nil {
		return ""
	}
	return o.ActivityUUID
}

type CancelServerActivitiesErrors struct {
	Code    *float64 `json:"code,omitempty"`
	Message *string  `json:"message,omitempty"`
	Status  *float64 `json:"status,omitempty"`
}

func (o *CancelServerActivitiesErrors) GetCode() *float64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *CancelServerActivitiesErrors) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *CancelServerActivitiesErrors) GetStatus() *float64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// CancelServerActivitiesResponseBody - Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
type CancelServerActivitiesResponseBody struct {
	Errors []CancelServerActivitiesErrors `json:"errors,omitempty"`
}

func (o *CancelServerActivitiesResponseBody) GetErrors() []CancelServerActivitiesErrors {
	if o == nil {
		return nil
	}
	return o.Errors
}

type CancelServerActivitiesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
	Object *CancelServerActivitiesResponseBody
}

func (o *CancelServerActivitiesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CancelServerActivitiesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CancelServerActivitiesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CancelServerActivitiesResponse) GetObject() *CancelServerActivitiesResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
