// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetHomeDataErrors struct {
	Code    *float64 `json:"code,omitempty"`
	Message *string  `json:"message,omitempty"`
	Status  *float64 `json:"status,omitempty"`
}

func (o *GetHomeDataErrors) GetCode() *float64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *GetHomeDataErrors) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *GetHomeDataErrors) GetStatus() *float64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// GetHomeDataPlexResponseBody - Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
type GetHomeDataPlexResponseBody struct {
	Errors []GetHomeDataErrors `json:"errors,omitempty"`
}

func (o *GetHomeDataPlexResponseBody) GetErrors() []GetHomeDataErrors {
	if o == nil {
		return nil
	}
	return o.Errors
}

// GetHomeDataResponseBody - Home Data
type GetHomeDataResponseBody struct {
	ID            *float64 `json:"id,omitempty"`
	Name          *string  `json:"name,omitempty"`
	GuestUserID   *float64 `json:"guestUserID,omitempty"`
	GuestUserUUID *string  `json:"guestUserUUID,omitempty"`
	GuestEnabled  *bool    `json:"guestEnabled,omitempty"`
	Subscription  *bool    `json:"subscription,omitempty"`
}

func (o *GetHomeDataResponseBody) GetID() *float64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *GetHomeDataResponseBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *GetHomeDataResponseBody) GetGuestUserID() *float64 {
	if o == nil {
		return nil
	}
	return o.GuestUserID
}

func (o *GetHomeDataResponseBody) GetGuestUserUUID() *string {
	if o == nil {
		return nil
	}
	return o.GuestUserUUID
}

func (o *GetHomeDataResponseBody) GetGuestEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.GuestEnabled
}

func (o *GetHomeDataResponseBody) GetSubscription() *bool {
	if o == nil {
		return nil
	}
	return o.Subscription
}

type GetHomeDataResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Home Data
	TwoHundredApplicationJSONObject *GetHomeDataResponseBody
	// Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
	FourHundredAndOneApplicationJSONObject *GetHomeDataPlexResponseBody
}

func (o *GetHomeDataResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetHomeDataResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetHomeDataResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetHomeDataResponse) GetTwoHundredApplicationJSONObject() *GetHomeDataResponseBody {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONObject
}

func (o *GetHomeDataResponse) GetFourHundredAndOneApplicationJSONObject() *GetHomeDataPlexResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredAndOneApplicationJSONObject
}
