// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetSourceConnectionInformationRequest struct {
	// The source identifier with an included prefix.
	Source string `queryParam:"style=form,explode=true,name=source"`
}

func (o *GetSourceConnectionInformationRequest) GetSource() string {
	if o == nil {
		return ""
	}
	return o.Source
}

type GetSourceConnectionInformationErrors struct {
	Code    *float64 `json:"code,omitempty"`
	Message *string  `json:"message,omitempty"`
	Status  *float64 `json:"status,omitempty"`
}

func (o *GetSourceConnectionInformationErrors) GetCode() *float64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *GetSourceConnectionInformationErrors) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *GetSourceConnectionInformationErrors) GetStatus() *float64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// GetSourceConnectionInformationResponseBody - Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
type GetSourceConnectionInformationResponseBody struct {
	Errors []GetSourceConnectionInformationErrors `json:"errors,omitempty"`
}

func (o *GetSourceConnectionInformationResponseBody) GetErrors() []GetSourceConnectionInformationErrors {
	if o == nil {
		return nil
	}
	return o.Errors
}

type GetSourceConnectionInformationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
	Object *GetSourceConnectionInformationResponseBody
}

func (o *GetSourceConnectionInformationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetSourceConnectionInformationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetSourceConnectionInformationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetSourceConnectionInformationResponse) GetObject() *GetSourceConnectionInformationResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
