// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type LogMultiLineErrors struct {
	Code    *float64 `json:"code,omitempty"`
	Message *string  `json:"message,omitempty"`
	Status  *float64 `json:"status,omitempty"`
}

func (o *LogMultiLineErrors) GetCode() *float64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *LogMultiLineErrors) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *LogMultiLineErrors) GetStatus() *float64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// LogMultiLineResponseBody - Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
type LogMultiLineResponseBody struct {
	Errors []LogMultiLineErrors `json:"errors,omitempty"`
}

func (o *LogMultiLineResponseBody) GetErrors() []LogMultiLineErrors {
	if o == nil {
		return nil
	}
	return o.Errors
}

type LogMultiLineResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
	Object *LogMultiLineResponseBody
}

func (o *LogMultiLineResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *LogMultiLineResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *LogMultiLineResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *LogMultiLineResponse) GetObject() *LogMultiLineResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
