// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type StartAllTasksErrors struct {
	Code    *float64 `json:"code,omitempty"`
	Message *string  `json:"message,omitempty"`
	Status  *float64 `json:"status,omitempty"`
}

func (o *StartAllTasksErrors) GetCode() *float64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *StartAllTasksErrors) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *StartAllTasksErrors) GetStatus() *float64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// StartAllTasksResponseBody - Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
type StartAllTasksResponseBody struct {
	Errors []StartAllTasksErrors `json:"errors,omitempty"`
}

func (o *StartAllTasksResponseBody) GetErrors() []StartAllTasksErrors {
	if o == nil {
		return nil
	}
	return o.Errors
}

type StartAllTasksResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
	Object *StartAllTasksResponseBody
}

func (o *StartAllTasksResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *StartAllTasksResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *StartAllTasksResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *StartAllTasksResponse) GetObject() *StartAllTasksResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
