// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type UpdatePlayProgressRequest struct {
	// the media key
	Key string `queryParam:"style=form,explode=true,name=key"`
	// The time, in milliseconds, used to set the media playback progress.
	Time float64 `queryParam:"style=form,explode=true,name=time"`
	// The playback state of the media item.
	State string `queryParam:"style=form,explode=true,name=state"`
}

func (o *UpdatePlayProgressRequest) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *UpdatePlayProgressRequest) GetTime() float64 {
	if o == nil {
		return 0.0
	}
	return o.Time
}

func (o *UpdatePlayProgressRequest) GetState() string {
	if o == nil {
		return ""
	}
	return o.State
}

type UpdatePlayProgressErrors struct {
	Code    *float64 `json:"code,omitempty"`
	Message *string  `json:"message,omitempty"`
	Status  *float64 `json:"status,omitempty"`
}

func (o *UpdatePlayProgressErrors) GetCode() *float64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *UpdatePlayProgressErrors) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *UpdatePlayProgressErrors) GetStatus() *float64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// UpdatePlayProgressResponseBody - Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
type UpdatePlayProgressResponseBody struct {
	Errors []UpdatePlayProgressErrors `json:"errors,omitempty"`
}

func (o *UpdatePlayProgressResponseBody) GetErrors() []UpdatePlayProgressErrors {
	if o == nil {
		return nil
	}
	return o.Errors
}

type UpdatePlayProgressResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
	Object *UpdatePlayProgressResponseBody
}

func (o *UpdatePlayProgressResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdatePlayProgressResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdatePlayProgressResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdatePlayProgressResponse) GetObject() *UpdatePlayProgressResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
