// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdk

type Plex struct {
	Tv *Tv

	sdkConfiguration sdkConfiguration
}

func newPlex(sdkConfig sdkConfiguration) *Plex {
	return &Plex{
		sdkConfiguration: sdkConfig,
		Tv:               newTv(sdkConfig),
	}
}
