// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeletePlaylistRequest struct {
	// the ID of the playlist
	PlaylistID float64 `pathParam:"style=simple,explode=false,name=playlistID"`
}

func (o *DeletePlaylistRequest) GetPlaylistID() float64 {
	if o == nil {
		return 0.0
	}
	return o.PlaylistID
}

type DeletePlaylistErrors struct {
	Code    *float64 `json:"code,omitempty"`
	Message *string  `json:"message,omitempty"`
	Status  *float64 `json:"status,omitempty"`
}

func (o *DeletePlaylistErrors) GetCode() *float64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *DeletePlaylistErrors) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *DeletePlaylistErrors) GetStatus() *float64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// DeletePlaylistResponseBody - Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
type DeletePlaylistResponseBody struct {
	Errors []DeletePlaylistErrors `json:"errors,omitempty"`
}

func (o *DeletePlaylistResponseBody) GetErrors() []DeletePlaylistErrors {
	if o == nil {
		return nil
	}
	return o.Errors
}

type DeletePlaylistResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
	Object *DeletePlaylistResponseBody
}

func (o *DeletePlaylistResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeletePlaylistResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeletePlaylistResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeletePlaylistResponse) GetObject() *DeletePlaylistResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
