// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type EnablePaperTrailErrors struct {
	Code    *float64 `json:"code,omitempty"`
	Message *string  `json:"message,omitempty"`
	Status  *float64 `json:"status,omitempty"`
}

func (o *EnablePaperTrailErrors) GetCode() *float64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *EnablePaperTrailErrors) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *EnablePaperTrailErrors) GetStatus() *float64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// EnablePaperTrailResponseBody - Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
type EnablePaperTrailResponseBody struct {
	Errors []EnablePaperTrailErrors `json:"errors,omitempty"`
}

func (o *EnablePaperTrailResponseBody) GetErrors() []EnablePaperTrailErrors {
	if o == nil {
		return nil
	}
	return o.Errors
}

type EnablePaperTrailResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
	Object *EnablePaperTrailResponseBody
}

func (o *EnablePaperTrailResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *EnablePaperTrailResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *EnablePaperTrailResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *EnablePaperTrailResponse) GetObject() *EnablePaperTrailResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
