// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetLatestLibraryItemsRequest struct {
	// the Id of the library to query
	SectionID float64 `pathParam:"style=simple,explode=false,name=sectionId"`
	// item type
	Type float64 `queryParam:"style=form,explode=true,name=type"`
	// the filter parameter
	Filter *string `queryParam:"style=form,explode=true,name=filter"`
}

func (o *GetLatestLibraryItemsRequest) GetSectionID() float64 {
	if o == nil {
		return 0.0
	}
	return o.SectionID
}

func (o *GetLatestLibraryItemsRequest) GetType() float64 {
	if o == nil {
		return 0.0
	}
	return o.Type
}

func (o *GetLatestLibraryItemsRequest) GetFilter() *string {
	if o == nil {
		return nil
	}
	return o.Filter
}

type GetLatestLibraryItemsErrors struct {
	Code    *float64 `json:"code,omitempty"`
	Message *string  `json:"message,omitempty"`
	Status  *float64 `json:"status,omitempty"`
}

func (o *GetLatestLibraryItemsErrors) GetCode() *float64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *GetLatestLibraryItemsErrors) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *GetLatestLibraryItemsErrors) GetStatus() *float64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// GetLatestLibraryItemsResponseBody - Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
type GetLatestLibraryItemsResponseBody struct {
	Errors []GetLatestLibraryItemsErrors `json:"errors,omitempty"`
}

func (o *GetLatestLibraryItemsResponseBody) GetErrors() []GetLatestLibraryItemsErrors {
	if o == nil {
		return nil
	}
	return o.Errors
}

type GetLatestLibraryItemsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
	Object *GetLatestLibraryItemsResponseBody
}

func (o *GetLatestLibraryItemsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetLatestLibraryItemsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetLatestLibraryItemsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetLatestLibraryItemsResponse) GetObject() *GetLatestLibraryItemsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
