// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetMetadataRequest struct {
	// the id of the library item to return the children of.
	RatingKey float64 `pathParam:"style=simple,explode=false,name=ratingKey"`
}

func (o *GetMetadataRequest) GetRatingKey() float64 {
	if o == nil {
		return 0.0
	}
	return o.RatingKey
}

type GetMetadataErrors struct {
	Code    *float64 `json:"code,omitempty"`
	Message *string  `json:"message,omitempty"`
	Status  *float64 `json:"status,omitempty"`
}

func (o *GetMetadataErrors) GetCode() *float64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *GetMetadataErrors) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *GetMetadataErrors) GetStatus() *float64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// GetMetadataResponseBody - Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
type GetMetadataResponseBody struct {
	Errors []GetMetadataErrors `json:"errors,omitempty"`
}

func (o *GetMetadataResponseBody) GetErrors() []GetMetadataErrors {
	if o == nil {
		return nil
	}
	return o.Errors
}

type GetMetadataResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
	Object *GetMetadataResponseBody
}

func (o *GetMetadataResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetMetadataResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetMetadataResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetMetadataResponse) GetObject() *GetMetadataResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
