// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetServerListErrors struct {
	Code    *float64 `json:"code,omitempty"`
	Message *string  `json:"message,omitempty"`
	Status  *float64 `json:"status,omitempty"`
}

func (o *GetServerListErrors) GetCode() *float64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *GetServerListErrors) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *GetServerListErrors) GetStatus() *float64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// GetServerListServerResponseBody - Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
type GetServerListServerResponseBody struct {
	Errors []GetServerListErrors `json:"errors,omitempty"`
}

func (o *GetServerListServerResponseBody) GetErrors() []GetServerListErrors {
	if o == nil {
		return nil
	}
	return o.Errors
}

type GetServerListServer struct {
	Name              *string  `json:"name,omitempty"`
	Host              *string  `json:"host,omitempty"`
	Address           *string  `json:"address,omitempty"`
	Port              *float64 `json:"port,omitempty"`
	MachineIdentifier *string  `json:"machineIdentifier,omitempty"`
	Version           *string  `json:"version,omitempty"`
}

func (o *GetServerListServer) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *GetServerListServer) GetHost() *string {
	if o == nil {
		return nil
	}
	return o.Host
}

func (o *GetServerListServer) GetAddress() *string {
	if o == nil {
		return nil
	}
	return o.Address
}

func (o *GetServerListServer) GetPort() *float64 {
	if o == nil {
		return nil
	}
	return o.Port
}

func (o *GetServerListServer) GetMachineIdentifier() *string {
	if o == nil {
		return nil
	}
	return o.MachineIdentifier
}

func (o *GetServerListServer) GetVersion() *string {
	if o == nil {
		return nil
	}
	return o.Version
}

type GetServerListMediaContainer struct {
	Size   *float64              `json:"size,omitempty"`
	Server []GetServerListServer `json:"Server,omitempty"`
}

func (o *GetServerListMediaContainer) GetSize() *float64 {
	if o == nil {
		return nil
	}
	return o.Size
}

func (o *GetServerListMediaContainer) GetServer() []GetServerListServer {
	if o == nil {
		return nil
	}
	return o.Server
}

// GetServerListResponseBody - List of Servers
type GetServerListResponseBody struct {
	MediaContainer *GetServerListMediaContainer `json:"MediaContainer,omitempty"`
}

func (o *GetServerListResponseBody) GetMediaContainer() *GetServerListMediaContainer {
	if o == nil {
		return nil
	}
	return o.MediaContainer
}

type GetServerListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of Servers
	TwoHundredApplicationJSONObject *GetServerListResponseBody
	// Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
	FourHundredAndOneApplicationJSONObject *GetServerListServerResponseBody
}

func (o *GetServerListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetServerListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetServerListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetServerListResponse) GetTwoHundredApplicationJSONObject() *GetServerListResponseBody {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONObject
}

func (o *GetServerListResponse) GetFourHundredAndOneApplicationJSONObject() *GetServerListServerResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredAndOneApplicationJSONObject
}
