// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetUpdateStatusErrors struct {
	Code    *float64 `json:"code,omitempty"`
	Message *string  `json:"message,omitempty"`
	Status  *float64 `json:"status,omitempty"`
}

func (o *GetUpdateStatusErrors) GetCode() *float64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *GetUpdateStatusErrors) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *GetUpdateStatusErrors) GetStatus() *float64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// GetUpdateStatusResponseBody - Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
type GetUpdateStatusResponseBody struct {
	Errors []GetUpdateStatusErrors `json:"errors,omitempty"`
}

func (o *GetUpdateStatusResponseBody) GetErrors() []GetUpdateStatusErrors {
	if o == nil {
		return nil
	}
	return o.Errors
}

type GetUpdateStatusResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
	Object *GetUpdateStatusResponseBody
}

func (o *GetUpdateStatusResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetUpdateStatusResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetUpdateStatusResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetUpdateStatusResponse) GetObject() *GetUpdateStatusResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
