// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type StopTranscodeSessionRequest struct {
	// the Key of the transcode session to stop
	SessionKey string `pathParam:"style=simple,explode=false,name=sessionKey"`
}

func (o *StopTranscodeSessionRequest) GetSessionKey() string {
	if o == nil {
		return ""
	}
	return o.SessionKey
}

type StopTranscodeSessionErrors struct {
	Code    *float64 `json:"code,omitempty"`
	Message *string  `json:"message,omitempty"`
	Status  *float64 `json:"status,omitempty"`
}

func (o *StopTranscodeSessionErrors) GetCode() *float64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *StopTranscodeSessionErrors) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *StopTranscodeSessionErrors) GetStatus() *float64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// StopTranscodeSessionResponseBody - Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
type StopTranscodeSessionResponseBody struct {
	Errors []StopTranscodeSessionErrors `json:"errors,omitempty"`
}

func (o *StopTranscodeSessionResponseBody) GetErrors() []StopTranscodeSessionErrors {
	if o == nil {
		return nil
	}
	return o.Errors
}

type StopTranscodeSessionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
	Object *StopTranscodeSessionResponseBody
}

func (o *StopTranscodeSessionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *StopTranscodeSessionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *StopTranscodeSessionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *StopTranscodeSessionResponse) GetObject() *StopTranscodeSessionResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
