// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type StopAllTasksErrors struct {
	Code    *float64 `json:"code,omitempty"`
	Message *string  `json:"message,omitempty"`
	Status  *float64 `json:"status,omitempty"`
}

func (o *StopAllTasksErrors) GetCode() *float64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *StopAllTasksErrors) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *StopAllTasksErrors) GetStatus() *float64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// StopAllTasksResponseBody - Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
type StopAllTasksResponseBody struct {
	Errors []StopAllTasksErrors `json:"errors,omitempty"`
}

func (o *StopAllTasksResponseBody) GetErrors() []StopAllTasksErrors {
	if o == nil {
		return nil
	}
	return o.Errors
}

type StopAllTasksResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
	Object *StopAllTasksResponseBody
}

func (o *StopAllTasksResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *StopAllTasksResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *StopAllTasksResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *StopAllTasksResponse) GetObject() *StopAllTasksResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
